"""initial migration

Revision ID: 48acbf73a83f
Revises: 
Create Date: 2025-07-31 09:16:54.422934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48acbf73a83f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('event_name', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preset',
    sa.Column('name', sa.String(length=50), nullable=False, comment='Название пресета'),
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spellbook',
    sa.Column('round_num', sa.String(length=3), nullable=False, comment='Номер раунда'),
    sa.Column('kick_num', sa.String(length=3), nullable=False, comment='Номер удара'),
    sa.Column('preset_id', sa.Integer(), nullable=False, comment='ID связанного пресета'),
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['preset_id'], ['preset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slotspell',
    sa.Column('page_num', sa.String(length=10), nullable=False, comment='Номер страницы'),
    sa.Column('slot_num', sa.String(length=10), nullable=False, comment='Номер слота'),
    sa.Column('spell_name', sa.String(length=100), nullable=True, comment='Название заклинания'),
    sa.Column('spell_book_id', sa.Integer(), nullable=False, comment='ID связанной книги заклинаний'),
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['spell_book_id'], ['spellbook.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slotspell')
    op.drop_table('spellbook')
    op.drop_table('preset')
    op.drop_table('event')
    # ### end Alembic commands ###
