"""Added useraccess table

Revision ID: 93bd1d3b1fdf
Revises: fc813792454e
Create Date: 2025-09-26 10:07:55.965465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93bd1d3b1fdf'
down_revision: Union[str, Sequence[str], None] = 'fc813792454e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useraccess',
    sa.Column('username', sa.String(length=100), nullable=True, comment='Ник персонажа'),
    sa.Column('access', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('event', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('preset', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('slotspell', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('spellbook', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spellbook', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('slotspell', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('preset', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('event', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_table('useraccess')
    # ### end Alembic commands ###
