"""spell book model create

Revision ID: d05c22406a19
Revises: 725b72902557
Create Date: 2025-07-15 14:44:01.711387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd05c22406a19'
down_revision: Union[str, Sequence[str], None] = '725b72902557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spellbook',
    sa.Column('preset_name', sa.String(length=10), nullable=False),
    sa.Column('round', sa.String(length=3), nullable=False),
    sa.Column('strike', sa.String(length=3), nullable=False),
    sa.Column('slot', sa.String(length=1), nullable=False),
    sa.Column('spell', sa.String(length=1), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spellbook')
    # ### end Alembic commands ###
